### ISSUE TITLE
Develop coarse grained (public) geocoding API

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#11]
- [x] Address parsing #56 
- [x] Single geocode #45 
- [x] Batch geocode #46
- [x] Configure ElasticSearch for batch geocoding #47 
- [x] Search multiple data sources #48 
- [x] Return source information #49 
- [x] Business rules for cascading #79 
- [ ] Assign score to geocoding result #50 
- [x] Failure response if geocode not found #51 
- [ ] Pass source and score to the UI #52 
- [x] Translate user's request to geocode from a specific datasource #53 
- [x] Return for single geocode API #54  
- [x] Return for batch geocode API #55 
- [x] Microservice aggregation #57

**Comment by wpears** [comment]
So I was thinking about this a bit this morning and we'll probably end up POSTing batch geocodes, since we'd run into size limits fairly early for querystrings.

Dunno if we want to implement some sort of request batching in the clientside API to internally limit the size of the message body so that the web server doesn't hang when parsing an, eg, ~20mb address file.

Larger requests limit http overhead and would take advantage of any batch queries the db supports.

Downsides of this approach are you can't necessarily get results until you've sent the entire query to the server. Also if one/several large queries fail, no data comes back, rather than getting most of the results if each individual address was requested separately.

This probably can't be answered completely until we are certain about what the initial web server will be for the entry point into the server-side API and we do some benchmarking... but until then, thoughts?

**Comment by jmarin** [comment]
I'd like to explore some streaming concepts to see where that gets us (chunked request / response). Also, it's not out of the question (and probably what we'll end up doing, it just makes sense) to impose a limit on batch geocoding, i.e. x thousand records or x MB of file size in one go.

**Comment by wpears** [comment]
Doing some rough work [in this repo](https://github.com/wpears/grassjs).
