### ISSUE TITLE
Geocoding service metrics

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#14]
The geocoding service needs to capture metrics of its runtime performance. Metrics should be stored and able to be queried on demand
- [ ] Tools for metrics logging #72 
- [ ] Point geocode execution time #37 
- [ ] 404 errors #73 
- [ ] System health #74 
- [ ] Usage of system #75 
- [ ] Address error rate #76 
- [ ] Metrics UI display #78
