### ISSUE TITLE
Geocoding documentation

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#16]
High level documentation for the project. Assumptions, known limitations, scope and technical approach
- [ ] Architecture diagram #15 
- [ ] API documentation #13 
- [ ] Coarse grained API spec #10 
- [ ] Fine grained API spec #6 
- [ ] TIGER geocoding spec #9 
- [x] Point address geocoding spec #7 
- [ ] Microservices schema #71
