### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#17]
- [x] Investigate microservices deployment and service discovery options #66 
- [x]  Set up AWS #67 
- [x] Metaservice #68 
- [x] Mesos - Standalone or with Marathon #69 
- [x] Service discovery #70

**Comment by jmarin** [comment]
This will be tracked in separate repository. Closing
