### ISSUE TITLE
Data model specification

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#5]
Specify data model for data exchange and storage, for all data types used for geocoding
- [x]  Point data exchange spec #4 
- [x]  Internal data structure point geocoding (ES schema) #23
- [ ]  Internal data structure line geocoding (ES schema) #24
- [ ]  Capture source of data #28
- [ ]  Capture internal data receipt and load timestamp #41
- [ ]  TIGER data model #42 
- [ ]  ElasticSearch data mapping #43
- [ ]  Seeing past geocode results #44
- [ ]  Parse unusual addresses #81

**Comment by jmarin** [comment]
Address points authoritative data source exchange format #4
