### ISSUE TITLE
Develop fine grained API endpoints

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#8]
Depends on #6
- [ ] Address parsing
- [ ] Individual microservices #59 
- [x] Point geocoding service #7
- [ ] TIGER geocoding service #58 
- [ ] Generic geocode (i.e. zip code, gnis)
- [ ] End points #60 
- [ ] Fine grained API returns #61
- [ ] Distinguishing which year's data to use #62 
- [x] Census API #63 
- [ ] Yearly census data storing #64 
- [ ] Using score for choosing a data source #65 
- [x] Point in Poly #80
